// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { Footer } from "@/components/footer";
import HeaderComponent from "@/components/header";
// 1. Importez le ThemeProvider
import { ThemeProvider } from '@/context/theme-provider'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 2. Ajoutez suppressHydrationWarning et retirez les classes de thème ici
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 3. ENVELOPPEZ tout le contenu visible avec le ThemeProvider */}
        <ThemeProvider>
          <HeaderComponent />
          {children}
          <Footer />
        </ThemeProvider>
        
        {/* Laissez Analytics en dehors du ThemeProvider si vous le souhaitez, mais il est souvent mieux de le laisser ici */}
        <Analytics />
      </body>
    </html>
  );
}